kind: pipeline
type: kubernetes
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo dockerh

---

kind: pipeline
type: docker
name: default2
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo dockerh
