kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello444
  - echo dockerh444ff

---
kind: signature
hmac: 724067f1dabf95302514c8d914c1fdfba12ca90f018a4b706928901c06c6db8c

